# Generated by Django 5.2.8 on 2026-03-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_deliverysettings_pincodelocationcache_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_hero_image', models.URLField(blank=True, max_length=1000, null=True)),
                ('home_category_oversized_image', models.URLField(blank=True, max_length=1000, null=True)),
                ('home_category_minimal_image', models.URLField(blank=True, max_length=1000, null=True)),
                ('home_category_printed_image', models.URLField(blank=True, max_length=1000, null=True)),
                ('home_feature_shipping_image', models.URLField(blank=True, max_length=1000, null=True)),
                ('home_feature_returns_image', models.URLField(blank=True, max_length=1000, null=True)),
                ('home_feature_payment_image', models.URLField(blank=True, max_length=1000, null=True)),
                ('home_feature_support_image', models.URLField(blank=True, max_length=1000, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'General Settings',
                'verbose_name_plural': 'General Settings',
            },
        ),
    ]
