# Generated by Django 5.2.8 on 2026-03-28 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_generalsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsettings',
            name='home_feature_payment_image',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='home_feature_returns_image',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='home_feature_shipping_image',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='home_feature_support_image',
        ),
    ]
