# Generated by Codex on 2026-03-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_id_alter_productimage_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
