# Generated by Django 5.2.8 on 2026-03-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_replace_theme_and_sleeve_with_category_fit_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bulk_order_min_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bulk_order_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
